# Generated by Django 4.1.4 on 2022-12-16 19:02

from django.db import migrations, models
import emailApp.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=45)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', emailApp.managers.UserManager()),
            ],
        ),
    ]
